[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { features = ["derive"], version = "1.0.147" }
bincode = "1.3.3"
sha3 = "0.10.6"